//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartAppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistinctTest
    {
        public int LOC_ID { get; set; }
        public string LOC_NAME { get; set; }
        public Nullable<double> LAT { get; set; }
        public Nullable<double> LONG { get; set; }
    }
}
