//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartAppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailConfigs
    {
        public int Id { get; set; }
        public string SmtpHost { get; set; }
        public string SmtpPort { get; set; }
        public string SmtpEmail { get; set; }
        public string SmtpPassword { get; set; }
        public string BccMail { get; set; }
        public string FromMail { get; set; }
        public string DisplayName { get; set; }
    }
}
