//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartAppModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StartAppEntities : DbContext
    {
        public StartAppEntities()
            : base("name=StartAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddedByUserProducts> AddedByUserProducts { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<AllProducts> AllProducts { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<ContactForms> ContactForms { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<DistinctTest> DistinctTest { get; set; }
        public virtual DbSet<Districts> Districts { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<LanguageTexts> LanguageTexts { get; set; }
        public virtual DbSet<MainCategories> MainCategories { get; set; }
        public virtual DbSet<PlaceCategories> PlaceCategories { get; set; }
        public virtual DbSet<PlaceMostPreferredProducts> PlaceMostPreferredProducts { get; set; }
        public virtual DbSet<PlaceProducts> PlaceProducts { get; set; }
        public virtual DbSet<PlaceProperties> PlaceProperties { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<PlaceTypes> PlaceTypes { get; set; }
        public virtual DbSet<Properties> Properties { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserDistricts> UserDistricts { get; set; }
        public virtual DbSet<UserFavoritePlaces> UserFavoritePlaces { get; set; }
        public virtual DbSet<UserFavoriteProducts> UserFavoriteProducts { get; set; }
        public virtual DbSet<UserFavoriteProperties> UserFavoriteProperties { get; set; }
        public virtual DbSet<UserPlaceRequests> UserPlaceRequests { get; set; }
        public virtual DbSet<UserPoints> UserPoints { get; set; }
        public virtual DbSet<UserPointTypes> UserPointTypes { get; set; }
        public virtual DbSet<UserRecommendedPlaces> UserRecommendedPlaces { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserSelectedCategories> UserSelectedCategories { get; set; }
        public virtual DbSet<UserSelectedMainCategories> UserSelectedMainCategories { get; set; }
        public virtual DbSet<UserSelectedProperties> UserSelectedProperties { get; set; }
        public virtual DbSet<UserTypes> UserTypes { get; set; }
        public virtual DbSet<UserVisitedPlaces> UserVisitedPlaces { get; set; }
        public virtual DbSet<CategoryProperties> CategoryProperties { get; set; }
        public virtual DbSet<BlogKeys> BlogKeys { get; set; }
        public virtual DbSet<Blogs> Blogs { get; set; }
        public virtual DbSet<ContentPlaces> ContentPlaces { get; set; }
        public virtual DbSet<Contents> Contents { get; set; }
    }
}
