//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartAppModel
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceCategories
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int PlaceId { get; set; }
        public string Note { get; set; }
        public bool IsActive { get; set; }

        [JsonIgnore]
        public virtual Categories Categories { get; set; }
        [JsonIgnore]
        public virtual Places Places { get; set; }
    }
}
