//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartAppModel
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Properties
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Properties()
        {
            this.PlaceProperties = new HashSet<PlaceProperties>();
            this.UserFavoriteProperties = new HashSet<UserFavoriteProperties>();
            this.UserSelectedProperties = new HashSet<UserSelectedProperties>();
            this.CategoryProperties = new HashSet<CategoryProperties>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string IconUrl { get; set; }
        public bool IsActive { get; set; }
        public int OrderNo { get; set; }
        public Nullable<bool> UserFavorite { get; set; }
        public bool tempSelect
        {
            get { return false; }
            set { }
        }
        public bool adminTempSelect { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<PlaceProperties> PlaceProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<UserFavoriteProperties> UserFavoriteProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<UserSelectedProperties> UserSelectedProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<CategoryProperties> CategoryProperties { get; set; }
    }
}
