//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartAppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFavoriteProducts
    {
        public int Id { get; set; }
        public int AllProductId { get; set; }
        public int UserId { get; set; }
        public System.DateTime RecordDate { get; set; }
    
        public virtual AllProducts AllProducts { get; set; }
        public virtual Users Users { get; set; }
    }
}
