//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartAppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSelectedMainCategories
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int MainCategoryId { get; set; }
    
        public virtual MainCategories MainCategories { get; set; }
        public virtual Users Users { get; set; }
    }
}
